version: '3.9'

services:
  eureka-server:
    image: charan0520/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  gateway:
    image: charan0520/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ecommerce-network

  users:
    image: charan0520/users-service
    container_name: users-service
    ports:
      - "8003:8003"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://charan20:Charan12345@cluster0.xsdi5.mongodb.net/usersDb?retryWrites=true&w=majority&appName=Cluster0
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ecommerce-network

  products:
    image: charan0520/products-service
    container_name: products-service
    ports:
      - "8002:8002"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://charan20:Charan12345@cluster0.xsdi5.mongodb.net/productsDb?retryWrites=true&w=majority&appName=Cluster0
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ecommerce-network

  orders:
    image: charan0520/orders-service
    container_name: orders-service
    ports:
      - "8001:8001"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://charan20:Charan12345@cluster0.xsdi5.mongodb.net/ordersDb?retryWrites=true&w=majority&appName=Cluster0
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
